---
tfg_k3s_cluster:
  children:
    server:
      hosts:
        tfg-k3s-morcilla:
    agent:
      hosts:
        tfg-k3s-salami:
        tfg-k3s-mortadela:

  vars:
    k3s_version: v1.30.2+k3s1
    token: 'ouJp8eX89mpkQL33+PLTopeIndVY+n486ND6oFxkeWt6ZZ5nEsfI4MziRIJVl6HiNMaHOCWB1ecxT/ASeswTUA=='
    api_endpoint: "{{ hostvars[groups['server'][0]]['ansible_host'] | default(groups['server'][0]) }}"
    cluster_context: tfg-k3s
    ansible_user: ansible
