$ANSIBLE_VAULT;1.1;AES256
65326634616265356537363863613864353634316239643031333238323233666138613832636264
6132393062333230356632613831333634396463356566380a353133623532363064663766326634
32613731353835346231656135623661333836326238636561383131636637653630616138393530
6266393361333461620a323432373761383532336332303537643666323733626231303463346535
39633461316135353137613261393165633038656438343536363562363634653365363530323236
35663734333165633162323338333139623661613836373536323436356432653433636431393165
303036616265396139303234653039373166
