---
- name: Install deps
  apt:
    name: parted

- name: Create primary partition
  parted:
    device: /dev/vda
    number: 1
    state: present

- name: Format partition
  filesystem:
    fstype: ext4
    dev: /dev/vda1

- name: Mount partition
  mount:
    fstype: ext4
    src: /dev/vda1
    path: /data
    state: mounted
