---
alu_username: alu0101410463
alu_ssh_key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMg5/0J6FR+4wICLeIWcCzdRgYj4PCfrFE69BHG0yvob jpiop@DESKTOP-L37VD5O
alu_passwd: $6$xyz$Qdt3ZrF78P0YvKG0SLBTnNM8DquvCLN/oCVuCG8jlYFRiU2dLxXFLCsGb30VGDTwHmuUjV8FxWlOZkt1dMljn0
